import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex min-h-screen flex-col items-center justify-between p-24'>
        <div className='z-[2] flex w-full max-w-[var(--max-width)] items-center justify-between text-[0.8rem] [font-family:_var(--font-mono)] sm:text-[0.85rem]'>
          <p className='relative m-0 rounded-xl border border-solid border-[rgba(var(--callout-border-rgb),_0.3)] bg-[rgba(var(--callout-rgb),_0.5)] p-4'>
            Get started by editing&nbsp;
            <code className='font-bold [font-family:_var(--font-mono)]'>
              src/pages/index.tsx
            </code>
          </p>
          <div>
            <a
              className='flex items-center justify-center gap-2 p-4 sm:p-0'
              href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              target='_blank'
              rel='noopener noreferrer'
            >
              By{' '}
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                className='dark:invert'
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className='center-logo'>
          <Image
            className='relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert'
            src='/next.svg'
            alt='Next.js Logo'
            width={180}
            height={37}
            priority
          />
          <div className="relative ml-4 flex h-[75px] w-[75px] items-center justify-center overflow-hidden rounded-[var(--border-radius)] from-[rgba(var(--tile-start-rgb),_1)] to-[rgba(var(--tile-end-rgb),_1)] bg-clip-content py-6 px-[10px] shadow-[0px_2px_8px_-1px_#0000001a] [transform:_translateZ(0)] before:absolute before:-z-[1] before:h-[200%] before:w-[200%] before:animate-[rotate_6s_linear_infinite] before:content-[''] before:[background:_var(--tile-border)] after:absolute after:inset-0 after:-z-[1] after:rounded-[var(--border-radius)] after:bg-gradient-to-br after:p-[1px] after:content-[''] motion-reduce:before:animate-none">
            <Image
              className='dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert'
              src='/thirteen.svg'
              alt='13'
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className='mb-32 grid w-[var(--max-width)] max-w-xs grid-cols-1 text-center sm:mb-0 sm:max-w-full sm:grid-cols-2 sm:text-left lg:grid-cols-[repeat(4,_minmax(25%,_auto))]'>
          <a
            href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className='group rounded-[var(--border-radius)] border border-solid border-[rgba(var(--card-border-rgb),_0)] py-4 px-10 [background:_rgba(var(--card-rgb),_0)] [transition:_background_200ms,_border_200ms] hover:border-[rgba(var(--card-border-rgb),_0.15)] hover:[background:_rgba(var(--card-rgb),_0.1)] sm:px-5'
            rel='noopener noreferrer'
          >
            <h2
              className={`${inter.className} mb-2 text-2xl font-semibold sm:mb-3`}
            >
              Docs{' '}
              <span className='inline-block transition-transform duration-200 group-hover:translate-x-1 motion-reduce:group-hover:transform-none'>
                -&gt;
              </span>
            </h2>
            <p
              className={`${inter.className} m-0 max-w-[30ch] text-[0.9rem] leading-6 opacity-60`}
            >
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className='group rounded-[var(--border-radius)] border border-solid border-[rgba(var(--card-border-rgb),_0)] py-4 px-10 [background:_rgba(var(--card-rgb),_0)] [transition:_background_200ms,_border_200ms] hover:border-[rgba(var(--card-border-rgb),_0.15)] hover:[background:_rgba(var(--card-rgb),_0.1)] sm:px-5'
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2
              className={`${inter.className} mb-2 text-2xl font-semibold sm:mb-3`}
            >
              Learn{' '}
              <span className='inline-block transition-transform duration-200 group-hover:translate-x-1 motion-reduce:group-hover:transform-none'>
                -&gt;
              </span>
            </h2>
            <p
              className={`${inter.className} m-0 max-w-[30ch] text-[0.9rem] leading-6 opacity-60`}
            >
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className='group rounded-[var(--border-radius)] border border-solid border-[rgba(var(--card-border-rgb),_0)] py-4 px-10 [background:_rgba(var(--card-rgb),_0)] [transition:_background_200ms,_border_200ms] hover:border-[rgba(var(--card-border-rgb),_0.15)] hover:[background:_rgba(var(--card-rgb),_0.1)] sm:px-5'
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2
              className={`${inter.className} mb-2 text-2xl font-semibold sm:mb-3`}
            >
              Templates{' '}
              <span className='inline-block transition-transform duration-200 group-hover:translate-x-1 motion-reduce:group-hover:transform-none'>
                -&gt;
              </span>
            </h2>
            <p
              className={`${inter.className} m-0 max-w-[30ch] text-[0.9rem] leading-6 opacity-60`}
            >
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className='group rounded-[var(--border-radius)] border border-solid border-[rgba(var(--card-border-rgb),_0)] py-4 px-10 [background:_rgba(var(--card-rgb),_0)] [transition:_background_200ms,_border_200ms] hover:border-[rgba(var(--card-border-rgb),_0.15)] hover:[background:_rgba(var(--card-rgb),_0.1)] sm:px-5'
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2
              className={`${inter.className} mb-2 text-2xl font-semibold sm:mb-3`}
            >
              Deploy{' '}
              <span className='inline-block transition-transform duration-200 group-hover:translate-x-1 motion-reduce:group-hover:transform-none'>
                -&gt;
              </span>
            </h2>
            <p
              className={`${inter.className} m-0 max-w-[30ch] text-[0.9rem] leading-6 opacity-60`}
            >
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
